services:
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD_ROOT}
      - MYSQL_USER=${USUARIO}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - "33306:3306"
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8100:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

volumes:
  mysql:
