services:
  web:
    build : .
    ports:
      - 8800:80
    volumes:
      - ./../app:/var/www/html
    container_name: web
    user: "${UID}:${GID}"
#    user: "www-data:www-data"


  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_DATABASE=tienda
    ports:
      - 33306:3306
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8100:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
volumes:
  mysql:



