services:
  web:
    build: docker/coolify/
    ports:
      - 80:80
    hostname: web
    container_name: web
  mysql:
    image: mysql
    ports:
      - 23306:3306
    environment:
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=alumnos
    volumes:
      - mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql: